idf_component_register(
    SRCS "main.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "ui_font_noto_sc_14.c"
         "ui_font_noto_sc_20.c"
         "ui_system.c"
         "ui_status.c"
         "app_settings.c"
         "wifi_manager.c"
         "time_sync.c"
         "demo_display.c"
         "demo_button.c"
         "demo_audio.c"
         "demo_battery.c"
         "demo_reader.c"
         "demo_settings.c"
         "demo_kiro_passport.c"
         "kiro_passport_ble.c"
    INCLUDE_DIRS "."
    REQUIRES bsp bt esp_event esp_http_server esp_netif esp_wifi lwip nvs_flash
)
